# Generated by Django 5.2.5 on 2026-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
