# Generated by Django 5.2.5 on 2026-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
