# Generated by Django 5.2.5 on 2026-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
